# Generated by Django 4.2.3 on 2023-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fullname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
